### Exercise 1. Linear Regression

This is a very simple exercise, we are going to load the movies dataset, and predict the variable `revenue` using the numerical variables.

In [17]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../data/movies.1.initial_process.csv")

In [3]:
movies.head()

,belongs_to_collection,budget,genre,original_language,popularity,production_company,production_country,release_date,revenue,runtime,status,title,vote_average,vote_count
0,Father of the Bride Collection,NaN,Comedy,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0
1,NaN,NaN,Drama,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,Released,"Cry, the Beloved Country",6.7,13.0
2,Friday Collection,3500000.0,Comedy,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Released,Friday,7.0,513.0
3,NaN,NaN,Comedy,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Released,Black Sheep,6.0,124.0
4,NaN,12000000.0,Comedy,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Released,Happy Gilmore,6.5,767.0

### Select the numerical columns and replace their missing values with 0

In [18]:
numerical_data = movies.select_dtypes(['int','float']).fillna(0).astype(np.float32)
numerical_data.head()

       budget  popularity     revenue  runtime  vote_average  vote_count
0         0.0    8.387519  76578912.0    106.0           5.7       173.0
1         0.0    0.894647    676525.0    106.0           6.7        13.0
2   3500000.0   14.569650  28215918.0     91.0           7.0       513.0
3         0.0    8.963037        32.0     87.0           6.0       124.0
4  12000000.0    9.592265  41205100.0     92.0           6.5       767.0

### Create a linear regression model and train it on the numerical variables, using the variable `revenue` as the target variable.

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
movie_model = LinearRegression()

In [15]:
names_independent_var = ['budget','popularity','runtime','vote_average','vote_count']

In [21]:
movie_model.fit(X=numerical_data[names_independent_var], y=numerical_data["revenue"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

### Create revenue predictions and assign them to a new column on the movies dataframe named `revenue_pred`.

In [22]:
movies["revenue_pred"] = movie_model.predict(numerical_data[names_independent_var])

In [23]:
movies.head()

,belongs_to_collection,budget,genre,original_language,popularity,production_company,production_country,release_date,revenue,runtime,status,title,vote_average,vote_count,revenue_pred
0,Father of the Bride Collection,NaN,Comedy,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0,13670409.0
1,NaN,NaN,Drama,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,Released,"Cry, the Beloved Country",6.7,13.0,5043133.5
2,Friday Collection,3500000.0,Comedy,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Released,Friday,7.0,513.0,38279000.0
3,NaN,NaN,Comedy,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Released,Black Sheep,6.0,124.0,9108447.0
4,NaN,12000000.0,Comedy,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Released,Happy Gilmore,6.5,767.0,67488976.0

### Print the revenue and revenue_pred columns for the first 10 rows

In [24]:
movies[['revenue','revenue_pred']].head(10)

       revenue  revenue_pred
0   76578911.0    13670409.0
1     676525.0     5043133.5
2   28215918.0    38279000.0
3         32.0     9108447.0
4   41205099.0    67488976.0
5     209935.0     3355838.0
6  185260553.0    61812696.0
7  355237933.0   175596592.0
8    1275000.0     4067810.5
9    3174695.0     8865066.0

In [26]:
normalized_model  = LinearRegression(normalize=True)
normalized_model.fit(X=numerical_data[names_independent_var],
                       y=numerical_data["revenue"])
movies["revenue_pred2"] = normalized_model.predict(numerical_data[names_independent_var])

In [27]:
movies.head()

,belongs_to_collection,budget,genre,original_language,popularity,production_company,production_country,release_date,revenue,runtime,status,title,vote_average,vote_count,revenue_pred,revenue_pred2
0,Father of the Bride Collection,NaN,Comedy,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0,13670409.0,13311821.0
1,NaN,NaN,Drama,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,Released,"Cry, the Beloved Country",6.7,13.0,5043133.5,5494084.0
2,Friday Collection,3500000.0,Comedy,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Released,Friday,7.0,513.0,38279000.0,38400936.0
3,NaN,NaN,Comedy,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Released,Black Sheep,6.0,124.0,9108447.0,9007135.0
4,NaN,12000000.0,Comedy,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Released,Happy Gilmore,6.5,767.0,67488976.0,67627800.0